// Generated by TypeQuery
import React from 'react';
import { useStaticQuery, graphql } from 'gatsby';
import Img, { FluidObject } from 'gatsby-image';

type GatsbyImageSharpFluidFragment = FluidObject & {
  /* ...GatsbyImageSharpFluid */
};

type PlaceholderImageStaticQuery = {
  placeholderImage?:/* file(relativePath: \\{ eq: "gatsby-astronaut.png" }) */ {
    childImageSharp: {
      fluid/* (maxWidth: 300) */: GatsbyImageSharpFluidFragment;
    };
  };
};

export const usePlaceholderImageStaticQuery = (): PlaceholderImageStaticQuery => {
    return useStaticQuery(graphql`
        query PlaceholderImageStaticQuery {
  placeholderImage?: file(relativePath: { eq: "gatsby-astronaut.png" })  {
    childImageSharp {
      fluid (maxWidth: 300) {...GatsbyImageSharpFluid}
    }
  }
}
    `);
};
