// Generated by TypeQuery
/**
 * Layout component that queries for data
 * with Gatsby's useStaticQuery component
 *
 * See: https://www.gatsbyjs.org/docs/use-static-query/
 */
import React, { ReactNode } from 'react';
import { useStaticQuery, graphql } from 'gatsby';
import { Header } from './header';
import './layout.css';

type SiteTileStaticQuery = {
  site: {
    siteMetadata: {
      title?: string;
      author?: string;
    };
  };
};

export const useSiteTileStaticQuery = (): SiteTileStaticQuery => {
  return useStaticQuery(graphql`
        query SiteTileStaticQuery {
  site {
    siteMetadata {
      title
      author
    }
  }
}
    `);
};
